# Generated by Django 3.0.6 on 2020-05-12 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gnólachtaí', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aicme',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Gnólacht',
            new_name='Product',
        ),
    ]
