# Generated by Django 3.0.6 on 2020-05-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='location',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
