# Generated by Django 3.0.6 on 2020-05-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='is_premium',
            new_name='has_sizes',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='business_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='business_hours',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='contact_details',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='location',
        ),
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
